config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  resources :cars, only: [:index, :show] do
    resources :reviews, only: :create
    # not sure if this needs to be nested .. probably will only be a button .. or should be
    resources :favorites, only: :create
  end
  resources :favorites, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :brand, :model, :year, presence: true
  validates :year, format: { with: /(19|20)\d{2}/, message: 'Must be in format XXXX' }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars

  validates :nickname, presence: true, uniqueness: true, length: { maximum: 20 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :comment, presence: true
  validates :rating, inclusion: { in: (1..5) }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @reviews = @car.reviews
    @review = Review.new
    @favorite = Favorite.new
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @favorite = Favorite.new
    @favorite.car = @car
    if @favorite.save
      redirect_to car_favorites_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @favorites = Favorite.all
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    redirect_to favorite_path(@favorite), status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
    if @review.save
      # need this even though it doesn't bring to new page
      redirect_to car_reviews_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/_car.html.erb
<% if favorite%>
  <div class="favorite-btn">
    <!--Want to put this inside car_img - how do I put this in the render-->
    <% if car.favorites.empty? %>
      <%= simple_form_for [car, favorite] do |f| %>
        <%= f.submit 'Add to favorites <3' %>
      <% end %>
    <% else %>
      <em><p>This car is already in your garage</p></em>
    <% end %>
  </div>
<% end %>

<div class="car-img" style="background-image: url(<%= car.image_url %>)">
</div>
<div class="d-flex flex-column justify-content-end">
  <div class="pe-3 align-self-end">
    <div class="owner-badge">
      <%= car.owner.nickname %>
    </div>
  </div>
  <div class="car-specs">
    <h3><%= link_to "#{car.brand} #{car.model}", car_path(car) %></h3>
    Year: <%= car.year %><br>
    <% if car.fuel.present? %>
      Fuel: <%= car.fuel.capitalize %><br>
    <% end %>
    <em style="font-size: 14px"><%= car.created_at.strftime("%A, %d %b %Y %l:%M %p") %></em>
  </div>
  <!--Add yield in here so that we can insert whole form on show,
  but on index, only a button that links to the review form section of the show page?-->
</div>

app/views/cars/index.html.erb
<div class="card-container">
  <% @cars.each do |car| %>
    <div class="car-card">
      <%= render 'car', car: car, favorite: nil%>
    </div>
  <% end %>
</div>

app/views/cars/show.html.erb
<!--Can I adapt the partial on this page?-->
<!--Because I'll want to add to it with the favorite button and comments etc-->
<div class="card-container">
  <div class="car-card">
    <%= render 'car', car: @car, favorite: @favorite%>

    <!--Make bootstrap list-->
    <ul class="list-group list-group-flush border-top border-bottom">
      <% @car.reviews.each do |review| %>
        <li class="list-group-item d-flex flex-row justify-content-between">
          <span><em><%= review.comment %></em></span>
          <span>
            <% if review.rating.present? %>
              <%= "★" * review.rating %>
            <% end %>
          </span>
        </li>
      <% end %>
    </ul>


    <div class="new-review-section">
      <p class="comment-btn">Leave a comment:</p>
      <!--drop down-->
      <div class="review-form">
        <%= simple_form_for [@car, @review] do |f| %>
          <%= f.input :comment %>
          <%= f.input :rating, collection: (1..5) %>
          <%= f.submit 'Submit', class: "button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<h1>My garage</h1>

<% @favorites.each do |favorite| %>
  <!--Can I make this a partial? Or just add class-->
  <h3><%= link_to favorite.car.brand, car_path(favorite.car) %></h3>
  <h4><%= favorite.car.model %></h4>
  <p><%= favorite.car.year %></p>
  <p><%= favorite.car.fuel %></p>
  <p><%= favorite.created_at %></p>
  <p><%= favorite.car.owner.nickname %></p>
  <%= link_to 'Delete',
    favorite_path(favorite),
    data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}
  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "🏁 Awesome Garage", root_path, class: "navbar-brand" %>
    <div class="navbar-nav d-flex flex-row">
      <%= link_to "Home", cars_path, class: "nav-link pe-3" %>
      <%= link_to "My garage", favorites_path, class: "nav-link" %>
    </div>
  </div>
</nav>